version: "3.7"

services:
    mysql:
        image: mysql:5.7
        env_file:
            - ".env"
        ports:
            - "3306:3306"
        volumes:
            - "estoes-challenge:/var/lib/mysql"

volumes:
    estoes-challenge:
